#! /bin/sh

### BEGIN INIT INFO
# Provides:          marv
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manage the marv rover
### END INIT INFO

. /lib/init/vars.sh
. /lib/lsb/init-functions
# If you need to source some other scripts, do it here

case "$1" in
  start)
    log_begin_msg "Starting marv rover"
    # do something
    log_end_msg $?
    exit 0
    ;;

  stop)
    log_begin_msg "Stopping marv rover"
    # do something to kill the service or cleanup or nothing
    log_end_msg $?
    exit 0
    ;;

  *)
    echo "Usage: /etc/init.d/marv {start|stop}"
    exit 1
    ;;
esac
